### PR TITLE
Initial import of map code from almossawi

### PR DESCRIPTION
**Pull request by sgarrity**
This PR adds the start of the map code that @almossawi sent me.

I have made some changes beyond @almossawi's original code-drop:
1. Moved the location of the .js files
2. Updated the path to the /static/data/\* files in the JS
3. Updated the icons/styles in the map legend (`.key`) to use the web-font icons and refactored some of the LESS/CSS to share icon/color styles between this list and the list in the main choice-modal
4. Updated the `.selected` map key items to use get styles from a class, rather than updating the styles inline with JS.
5. Moved the map-specific JS and CSS into map.\* files.

Known issues:
- the map is not vertically centered in tall/narrow viewports
- the map only scales to fit viewport on initial page load, not on subsequent resizes.

@pmclanahan and @almossawi, please review. Thanks.

### CODE REVIEW

**Comment by almossawi** [comment]
Thanks, @sgarrity. r+

**Comment by sgarrity** [comment]
I'm merging now, but @pmclanahan, can you give this a retro-active review, at least for general location of files, etc. when you're back at work? Thanks.

**Comment by pmclanahan** [comment]
Certainly. I'll get to it soon.

**Comment by pmclanahan** [comment]
It all looks good to me. Thanks @sgarrity.

**Pull request merged**
