### PR TITLE
Add aurora borealis/australis effects

### PR DESCRIPTION
**Pull request by sgarrity**
Fixes Bug 1003447

This could replace PR #175. The effect should be similar, but the images are implement as background images, removing the need for absolute positioning, z-index, etc. The bottom (southern) aurora (australis, as I've learned it is called) are also merged into a single PNG.

Since the aurora are mostly transparent and sit atop a background with some noise/grain already, I was able to get away with some lossy compression that cut the image sizes _way_ down as well.

### CODE REVIEW

**Comment by almossawi** [comment]
Yes, much better! I'd be in favor of merging this rather than PR #175

**Comment by pmclanahan** [comment]
Definitely a good start. Would be nice to have the australis animation back, but I agree about the perf concerns.

My only question is whether it interferes with, or perhaps should be avoided on mobile? Can we avoid even downloading the extra image weight for mobile?

**Comment by sgarrity** [comment]
> My only question is whether it interferes with, or perhaps should be avoided on mobile? Can we avoid even downloading the extra image weight for mobile?

Good point. It's easy enough to wrap these additional background images in the desktop-size media query so they won't load or display at all on mobile.

That said, they don't actually look too bad on mobile. It is two additional http requests, but only 30Kb. I could go either way.

**Comment by pmclanahan** [comment]
Either is fine with me too, just wanted to make sure we considered it.

**Comment by pmclanahan** [comment]
Talked with Martell on IRC and he said leaving them off of mobile is fine.

**Comment by sgarrity** [comment]
Update to move the new aurora background images into the desktop media queries (hidden for mobile).

**Comment by bensternthal** [comment]
@sgarrity are we waiting on anything for this one - do you need anyone else to take a look?

**Pull request merged**
