### PR TITLE
Update bart to deal with shared logs on dev and prod.

### PR DESCRIPTION
**Pull request by pmclanahan**
Proposal:
- Dev will run `bart_dev.sh` on cron every minute.
- Prod will run `bart.sh` on cron every minute.

Prod receives logs, processes them, and moves them to the NFS. Dev then grabs
the newest one, processes it, then gzips it so that it won't do it again.

Counter proposals and comments most welcome!

@jgmize

### CODE REVIEW

**Comment by jgmize** [comment]
1. bard_dev.sh has no mechanism to ensure it doesn't process the same log twice
2. we could dramatically reduce network io by compressing during the initial archive instead of after the dev processing
3. shell scripts are fine for simple things, but we may be approaching the level of complexity that would justify a python rewrite
4. not sure if it's worth it, but we could parameterize the firefox version to an environment variable or other configuration mechanism

**Comment by pmclanahan** [comment]
1. the mechanism is the gzip. It only looks for `glow.*.log` so the `.gz` files won't be in the list.
2. is this a problem? it could be. My guess (hope) is that this is on a separate interface and very fast. I'm not really worried with how quickly dev gets new logs as long as it doesn't slow the other things on prod to send them there.
3. Agreed. I was leaning that way for this, but shell tools are really good at the kinds of things we need to do for this. I'm still on the fence, but could be pushed over.
4. Yeah... at least a variable at the top of the file for easy updating when we're ready.

**Comment by jgmize** [comment]
1. missed that, thanks for clarifying
2. It's probably not a big deal, let's try it this way first and we can optimize later
3. It's definitely not worth blocking this PR, but if we make any significant changes I was thinking a rewrite using the python [sh module](http://amoffat.github.io/sh/) might be nice.
4. I'm fine with merging this as is and parameterize later, or if you want to parameterize it before merging that's cool too.

r+

**Comment by pmclanahan** [comment]
1. np
2. agreed
3. also agreed
4. added a commit to do the parametrization. 

Merge at will if you're happy, and we can then get jakem to move the logs.

**Pull request merged**
