### PR TITLE
Stats - placeholder for chart 3 now resizes

### PR DESCRIPTION
**Pull request by almossawi**
Modified the placeholder image, which appears when we have share data for fewer than 15 countries, so that it resizes appropriately when the window is resized.

### CODE REVIEW

**Comment by almossawi** [comment]
cc @sgarrity

**Comment by sgarrity** [comment]
Is there a way to get this state for testing?

**Comment by almossawi** [comment]
Yes, replace the if(... < 15) guard with if(true) in stats.js

**Comment by sgarrity** [comment]
In the mobile layout, the fixed height is larger than it needs to be, but I don't think we need to block on that.

**Comment by almossawi** [comment]
I'll make a note to fix that.

**Pull request merged**
