### PR TITLE
Fix bug #1001536

### PR DESCRIPTION
**Pull request by almossawi**

### CODE REVIEW

**Comment by almossawi** [comment]
@sgarrity The grain is hardly visible with the opacity reduced to 90%, and going lower than that affects the colors' tints. We currently have the grain effect in the map's 'off' state. Are the 'on' states acceptable as is, or would it be worthwhile to look into a different way to add the grain over the continents in said states?

**Comment by sgarrity** [comment]
I get the impression that Sean would like to see the grain on all color states (no pun intended), but at this point, we're making tradeoffs. Applying a background image to a shape in an SVG element does appear to be possible ([example](http://stackoverflow.com/questions/3796025/fill-svg-path-element-with-a-background-image)), but I'm not sure it's possible with a color as well, unless we duplicated/stack elements.

Another option would be a div with the background overlaid on top of the current map, using another SVG image as a mask.

I'm not sure either option is doable by tomorrow.

**Comment by almossawi** [comment]
I'd feel nervous making any drastic changes shortly before release, but I'll see what I can do tomorrow morning. 

Right now, you can see the difference between an alpha of 90% and that of no alpha by switching between 'user control' and 'region' on the map.

**Comment by almossawi** [comment]
Do you think the 90% alpha offers any value? It doesn't appear to, so I was considering reverting that change.

**Comment by sgarrity** [comment]
I'm not sure the 90% is worthwhile, no. I think we might be stuck on this one given how close to launch we are.

**Comment by almossawi** [comment]
We'd have to do it using an svg element since the grain would sit between the continents and the {glows, labels}. I'm experimenting with it right now, and my intuition is that we'd take a performance hit by adding a second set of continents on top of the existing ones in the map's 'on' state. I also worry about potential unintended consequences of such a change so close to release.

**Pull request merged**
