### PR TITLE
Add script to populate .po files from l10n JSON.

### PR DESCRIPTION
**Pull request by pmclanahan**
I've already run this script and the new following new strings are correct in
all of the locales:
- Get Involved
- FAQ

So this also unhides "Get Involved" for all locales.

### CODE REVIEW

**Comment by pmclanahan** [comment]
@sgarrity @bensternthal r?

**Comment by pmclanahan** [comment]
Since the strings are already in the locales repo, once this is merged we should see the "Get Involved" string fully translated in all locales on dev. The "FAQ" link is still hidden because there doesn't seem to be a URL for that link yet.

**Comment by pmclanahan** [comment]
Buler?

**Comment by bensternthal** [comment]
Confirm do not un-hide FAQ. The content for this is not written yet.

**Comment by pmclanahan** [comment]
Yeah. The Get Involved link is ready and translated though. And the new headline string is in and being translated.

**Comment by sgarrity** [comment]
Un-hiding of the Get Involved string is r+
The other script is over-my-head.

**Pull request merged**
