### PR TITLE
Maps and Stats tweaks

### PR DESCRIPTION
**Pull request by almossawi**
- Counter animates every 10s, this helps reduce cpu usage in Firefox.
- The median label in chart 3 on the stats page moves up by 20px when
  the median and min values are too close, to prevent them from
  overlapping.

### CODE REVIEW

**Comment by almossawi** [comment]
cc @sgarrity

**Comment by almossawi** [comment]
@sgarrity I took the liberty of experimenting with a few alternatives. I think your suggestion to just increment the counter every 10 or so seconds might not be a bad idea since the improvement in terms of cpu usage in Firefox is noticeable. I like the counter animation that we currently have, but wouldn't mind trading it for (slightly) better performance.

**Comment by pmclanahan** [comment]
Would something pre-made for this maybe contain some optimizations? e.g. http://github.hubspot.com/odometer/docs/welcome/

**Comment by almossawi** [comment]
Nice find. I did some quick testing. If we update the counter every 3s, the average CPU usage in Firefox on my machine, at present, is as follows for the three proposed methods:

~65% - using odometer
~40% - fading out then in 
~30% - just updating the count
(~70% - current method of continuously animating the counter)

Very rough estimates, of course, but they give a sense of what the landscape is. I'd vote for the option that has the least impact on performance, given that if the website does find the need to up the client's cpu usage, it would be best if it did so in order to show more glows rather than to maintain the counter's animation.

**Comment by sgarrity** [comment]
For reference, here's a rough mockup of the 'fading out then in every X seconds' method: http://jsfiddle.net/Fpj2k/

You can play with interval - it's the '2000' figure (milliseconds).

**Comment by almossawi** [comment]
@bensternthal

**Comment by bensternthal** [comment]
Interesting... so in addition to the cpu usage have you noticed a difference in responsiveness?

So using odometer with 60% cpu usage.. does the site feel faster or slower than the other techniques.

**Comment by almossawi** [comment]
I'm afraid I only looked at cpu usage and didn't test responsiveness. I noticed that odometer has a peculiar glitch in Firefox wherein the text nudges slightly before and after each transition, so I'm not sure if it will be worth trying to debug that, given that we only have a couple of days of development left. Or perhaps it's something simple, @sgarrity?

**Pull request merged**
