### PR TITLE
Fix bug 1003447 - add aurora borealis effects

### PR DESCRIPTION
**Pull request by almossawi**

### CODE REVIEW

**Comment by almossawi** [comment]
@sgarrity sean brought it to our attention that his beloved aurora borealis effects were never added to the map.

**Comment by almossawi** [comment]
@sgarrity If you could please review at your convenience.

**Comment by sgarrity** [comment]
Tried a different approach to the same effect in PR #176. Please take a look.

**Comment by sgarrity** [comment]
#176 is totally the new #175.

**Pull request closed without merging**
