### PR TITLE
Maps - added smooth transitioning between minutes

### PR DESCRIPTION
**Pull request by almossawi**
At the end of every minute, we append non-dead glows from the previous minute to the current data array and transition them out immediately.

### CODE REVIEW

**Comment by almossawi** [comment]
@pmclanahan It seems like the auto-deploy to dev is not working? No rush at all; just wanted to let you know.

**Comment by pmclanahan** [comment]
## Thanks. Been working on it this weekend. Haven't quite got it apparently. 

Sent from my mobile. Please excuse my brevity.

**Comment by pmclanahan** [comment]
Working again. All your recent changes should be live on dev now.

**Comment by almossawi** [comment]
Much appreciated!

**Pull request merged**
